In [3]:
import pandas as pd
df= pd.read_csv("marketing_campaign_data_messy.csv")

In [4]:
#Headers Cleaning
df.columns.to_list()
df.columns = df.columns.str.strip(" ").str.lower().str.replace(" ", "_")
df.columns.to_list()

['campaign_id',
 'campaign_name',
 'start_date',
 'end_date',
 'channel',
 'impressions',
 'clicks',
 'spend',
 'conversions',
 'active',
 'clicks',
 'campaign_tag']

In [13]:
#type conversion and currency cleaning
spend= df['spend'].astype(str).str.contains(r"\$")
print(df.loc[spend, ['campaign_id', 'spend']])
df["spend1"]= df['spend'].astype(str).str.replace(r'[^\d.\-]', '', regex= True)
df['spend1'] = df['spend1'].astype(float)
print(df.loc[spend, ['campaign_id', 'spend1']])

     campaign_id     spend
0      CMP-00001   $102.82
21     CMP-00022   $2428.4
22     CMP-00023  $4726.22
31     CMP-00032  $2759.35
32     CMP-00033  $2393.02
...          ...       ...
1992   CMP-01993   $755.86
2002   CMP-01426  $2640.72
2011   CMP-01028  $2422.76
2013   CMP-00388  $2135.23
2015   CMP-00400   $503.95

[298 rows x 2 columns]
     campaign_id   spend1
0      CMP-00001   102.82
21     CMP-00022  2428.40
22     CMP-00023  4726.22
31     CMP-00032  2759.35
32     CMP-00033  2393.02
...          ...      ...
1992   CMP-01993   755.86
2002   CMP-01426  2640.72
2011   CMP-01028  2422.76
2013   CMP-00388  2135.23
2015   CMP-00400   503.95

[298 rows x 2 columns]

/tmp/ipykernel_1372/1094300672.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["spend1"]= df['spend'].astype(str).str.replace(r'[^\d.\-]', '', regex= True)
/tmp/ipykernel_1372/1094300672.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spend1'] = df['spend1'].astype(float)

In [6]:
#Categorical Typos
import numpy as np
print(df['channel'].unique())
cleanup_map=  {
    'Facebok': "Facebook",
    'Insta_gram': 'Instagram',
    'Tik_Tok': 'TikTok',
    'E-mail': 'Email',
    'N/A': np.nan
}
df['channel']= df['channel'].replace(cleanup_map)
df

['TikTok' 'Facebook' 'Email' 'Instagram' 'Google Ads' 'E-mail' nan 'Gogle'
 'Tik_Tok' 'Facebok' 'Insta_gram']

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,clicks,campaign_tag,spend1
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI,102.82
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA,24.33
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM,1323.39
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI,2180.38
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA,252.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31 00:00:00,2023-11-13,TikTok,30592,586,$503.95,77.0,1,NaN,TI,503.95
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01 00:00:00,2023-09-26,Google Ads,20097,897,1641.0,162.0,0,NaN,GO,1641.0
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09 00:00:00,2023-02-21,Instagram,33254,1117,883.82,214.0,0,NaN,IN,883.82
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30 00:00:00,2023-04-27,Facebook,68728,2960,4198.5,591.0,Yes,NaN,FA,4198.5
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26 00:00:00,2023-07-09,Email,96402,1090,1315.59,66.0,Y,NaN,EM,1315.59

In [7]:
#handling booleans
print(df['active'].unique())
new_map= {
    'Yes': True,
    'No': False,
    1: True,
    0: False,
    'Y': True,
    'N': False
}
df['active']= df['active'].replace(new_map)

df

['Y' '0' 'No' 'True' 'Yes' '1' 'False']

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,clicks,campaign_tag,spend1
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,True,NaN,TI,102.82
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA,24.33
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,False,NaN,EM,1323.39
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI,2180.38
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,True,NaN,FA,252.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31 00:00:00,2023-11-13,TikTok,30592,586,$503.95,77.0,1,NaN,TI,503.95
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01 00:00:00,2023-09-26,Google Ads,20097,897,1641.0,162.0,0,NaN,GO,1641.0
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09 00:00:00,2023-02-21,Instagram,33254,1117,883.82,214.0,0,NaN,IN,883.82
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30 00:00:00,2023-04-27,Facebook,68728,2960,4198.5,591.0,True,NaN,FA,4198.5
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26 00:00:00,2023-07-09,Email,96402,1090,1315.59,66.0,True,NaN,EM,1315.59

In [8]:
#date parsing
print(df['start_date'].dtype)
df['start_date']= pd.to_datetime(df['start_date'], errors='coerce')
df['end_date']= pd.to_datetime(df['end_date'],dayfirst= True, errors='coerce')
df
df['start_date'].dtype

object

/tmp/ipykernel_1372/1351292451.py:4: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['end_date']= pd.to_datetime(df['end_date'],dayfirst= True, errors='coerce')

dtype('<M8[ns]')

In [9]:
df= df.loc[:, ~df.columns.duplicated()]
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag,spend1
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,$102.82,20.0,True,TI,102.82
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA,24.33
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,False,EM,1323.39
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,TI,2180.38
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,True,FA,252.44
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,$503.95,77.0,1,TI,503.95
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,1641.0,162.0,0,GO,1641.0
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,0,IN,883.82
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,4198.5,591.0,True,FA,4198.5
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,True,EM,1315.59

In [10]:
#logical integrity (time travel)
time_travel_mask= df['end_date'] < df['start_date']
df.loc[time_travel_mask, ['campaign_id', 'start_date', 'end_date']].head()
df.loc[time_travel_mask, 'end_date']= df.loc[time_travel_mask, 'start_date'] + pd.Timedelta(days=30)
print(df.loc[time_travel_mask, ['campaign_id', 'start_date', 'end_date']].head())

    campaign_id start_date   end_date
23    CMP-00024 2023-05-06 2023-06-05
54    CMP-00055 2023-09-01 2023-10-01
71    CMP-00072 2023-02-01 2023-03-03
156   CMP-00157 2023-12-06 2024-01-05
200   CMP-00201 2023-01-11 2023-02-10

In [17]:
#HANDLING OUTLIERS
df['spend1'] = df['spend1'].astype(float)
q1= df['spend1'].quantile(0.25)
q3= df['spend1'].quantile(0.75)
IQR= q3-q1
upper_limit = q3 + 1.5 * IQR
lower_limit = q1 - 1.5 * IQR
outlier_mask= (df['spend1'] > upper_limit) | (df['spend1'] < lower_limit)
print(df.loc[outlier_mask, ['campaign_id', 'spend1']])

     campaign_id   spend1
57     CMP-00058  5719.84
70     CMP-00071  5951.42
119    CMP-00120  7471.52
124    CMP-00125  6449.30
130    CMP-00131  6688.28
...          ...      ...
1896   CMP-01897  6335.34
1897   CMP-01898 -2503.31
1925   CMP-01926  8269.90
1944   CMP-01945  5924.19
1977   CMP-01978  5827.23

[76 rows x 2 columns]

/tmp/ipykernel_1372/4136344431.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spend1'] = df['spend1'].astype(float)

In [19]:
df['spend1']= df['spend1'].astype(float)
q1= df['spend1'].quantile(0.25)
q3= df['spend1'].quantile(0.75)
IQR= q3 - q1
upper_limit = q3 + 1.5 * IQR
lower_limit = q1 - 1.5 * IQR
mask= (df['spend1'] > upper_limit) | (df['spend1'] < lower_limit)
print(df.loc[mask, ['campaign_id', 'spend1']])
#df.loc[mask, 'spend1']= upper_limit

Empty DataFrame
Columns: [campaign_id, spend1]
Index: []

/tmp/ipykernel_1372/1184298931.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spend1']= df['spend1'].astype(float)

In [21]:
print(df['campaign_name'].head(3))

df['season'] = df['campaign_name'].str.extract(r'q\d_([^_]+)')

print(df[['campaign_name', 'season']].head(3))

0    Q4_Summer_CMP-00001
1    Q1_Launch_CMP-00002
2    Q3_Winter_CMP-00003
Name: campaign_name, dtype: object
         campaign_name season
0  Q4_Summer_CMP-00001    NaN
1  Q1_Launch_CMP-00002    NaN
2  Q3_Winter_CMP-00003    NaN